openapi: 3.0.3
info:
  title: Innoscripta
  version: 1.0.0
  contact: {}
servers:
  - url: http://localhost:8000
paths:
  /api/register:
    post:
      tags:
        - Auth
      summary: Register
      description: Register
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: umituz998@gmail.com
                name:
                  type: string
                  example: Ümit UZ
                password:
                  type: string
                  example: '123456789'
                password_confirmation:
                  type: string
                  example: '123456789'
            examples:
              Register:
                value:
                  email: umituz998@gmail.com
                  name: Ümit UZ
                  password: '123456789'
                  password_confirmation: '123456789'
      responses:
        '200':
          description: ''

  /api/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: umituz9999@gmail.com
                password:
                  type: string
                  example: '123456789'
            examples:
              Login:
                value:
                  email: umituz9999@gmail.com
                  password: '123456789'
      responses:
        '200':
          description: ''

  /api/logout:
    post:
      tags:
        - Auth
      summary: Logout
      description: Logout
      operationId: logout
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: umituz9999@gmail.com
                password:
                  type: string
                  example: '123456789'
            examples:
              Logout:
                value:
                  email: umituz9999@gmail.com
                  password: '123456789'
      responses:
        '200':
          description: ''

  /api/user/preferences:
    get:
      tags:
        - User
      summary: Preferences
      description: Preferences
      operationId: preferences1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sources:
                  type: array
                  items:
                    type: number
                    example: 1
                  example:
                    - 1
                    - 2
                    - 3
            examples:
              Preferences:
                value:
                  sources:
                    - 1
                    - 2
                    - 3
      responses:
        '200':
          description: ''

  /api/user/preferences/sources:
    post:
      tags:
        - User
      summary: Source Preferences
      description: Source Preferences
      operationId: sourcePreferences
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sourceIds:
                  type: array
                  items:
                    type: number
                    example: 1
                  example:
                    - 1
                    - 2
                    - 3
            examples:
              Source Preferences:
                value:
                  sourceIds:
                    - 1
                    - 2
                    - 3
      responses:
        '200':
          description: ''

  /api/user/preferences/categories:
    post:
      tags:
        - User
      summary: Category Preferences
      description: Category Preferences
      operationId: categoryPreferences
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryIds:
                  type: array
                  items:
                    type: number
                    example: 1
                  example:
                    - 1
                    - 2
                    - 3
            examples:
              Category Preferences:
                value:
                  categoryIds:
                    - 1
                    - 2
                    - 3
      responses:
        '200':
          description: ''

  /api/user/preferences/authors:
    post:
      tags:
        - User
      summary: Author Preferences
      description: Author Preferences
      operationId: authorPreferences
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authorIds:
                  type: array
                  items:
                    type: number
                    example: 1
                  example:
                    - 1
                    - 2
                    - 3
            examples:
              Author Preferences:
                value:
                  authorIds:
                    - 1
                    - 2
                    - 3
      responses:
        '200':
          description: ''

  /api/user:
    get:
      tags:
        - User
      summary: User
      description: User
      operationId: user
      responses:
        '200':
          description: ''

  /api/articles/preferences:
    get:
      tags:
        - Preference
      summary: Preferences
      description: Preferences
      operationId: preferences
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sources:
                  type: array
                  items:
                    type: number
                    example: 1
                  example:
                    - 1
                    - 2
                    - 3
            examples:
              Preferences:
                value:
                  sources:
                    - 1
                    - 2
                    - 3
      responses:
        '200':
          description: ''

  /api/articles:
    get:
      tags:
        - Article
      summary: Articles
      description: Articles
      operationId: articles
      responses:
        '200':
          description: ''

  /api/articles/scientists-hail-pioneering-software-in-hunt-for-alien-life:
    get:
      tags:
        - Article
      summary: Article Detail
      description: Article Detail
      operationId: articleDetail
      responses:
        '200':
          description: ''

tags:
  - name: Auth
  - name: Article
  - name: User
  - name: Preference
