stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: "backend-app"

backend:
  stage: build
  script:
    - apt-get update -y
    - apt-get install -y docker-compose
    - docker build -t $DOCKER_IMAGE -f Dockerfile .
    - docker run -d -p 8000:8000 --name $DOCKER_IMAGE $DOCKER_IMAGE

  after_script:
    - sleep 3
    - docker exec $DOCKER_IMAGE bash -c "touch backend/database/database.sqlite"
    - docker exec $DOCKER_IMAGE bash -c "sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/g' .env.testing"
    - docker exec $DOCKER_IMAGE bash -c "sed -i 's/DB_HOST=127.0.0.1/DB_HOST=:memory:/g' .env.testing"
    - docker exec $DOCKER_IMAGE bash -c "php artisan key:generate && php artisan migrate:fresh --seed --env=testing && php artisan test"
    - curl http://localhost:8000
