services:
    laravel.test:
        container_name: 'sail_laravel'
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - elasticsearch
            - mongodb
    mysql:
        container_name: 'sail_mysql'
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    postgresql:
        container_name: 'sail_postgresql'
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
        volumes:
            - 'sail-postgresql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
    phpmyadmin:
        container_name: 'sail_phpmyadmin'
        image: phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8080:80
        depends_on:
            - mysql
        networks:
            - sail
    phppgadmin:
        container_name: 'sail_phppgadmin'
        image: 'dpage/pgadmin4'
        environment:
            PGADMIN_DEFAULT_EMAIL: 'laravel@gmail.com'
            PGADMIN_DEFAULT_PASSWORD: 'password'
        ports:
            - 8083:80
        depends_on:
            - postgresql
        networks:
            - sail
    redis:
        container_name: 'sail_redis'
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    elasticsearch:
        container_name: 'sail_elasticsearch'
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.15.0'
        environment:
            - discovery.type=single-node
        ports:
            - '9200:9200'
        networks:
            - sail
    nodejs:
        container_name: 'sail_nodejs'
        build:
            context: ../microservices/nodejs
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        networks:
            - sail
        depends_on:
            - mongodb
    mongodb:
        container_name: 'sail_mongodb'
        image: mongo:4.4
        environment:
            MONGO_INITDB_DATABASE: mongodb
        ports:
            - "27017:27017"
        volumes:
            - 'sail-mongodb:/data/db'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 5s
            retries: 3

    mongodb-ui:
        container_name: 'sail_mongodb-ui'
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_BASICAUTH_USERNAME: laravel
            ME_CONFIG_BASICAUTH_PASSWORD: password
        ports:
            - 8081:8081
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-postgresql:
        driver: local
    sail-mongodb:
        driver: local
