name: TheFrontendProject

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
        working-directory: ./

      - name: Build and deploy Docker container
        run: |
          docker build -t frontend-app .
          docker run -d -p 3000:3000 frontend-app
        working-directory: ./

      - name: Wait for the container to start
        run: sleep 10

      - name: Test the application
        run: curl http://localhost:3000 
